from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Education_rank)
admin.site.register(Subject)
admin.site.register(Question)
admin.site.register(Post)
admin.site.register(Document)
admin.site.register(Answer)
admin.site.register(Bio)
admin.site.register(Comment_Post)
admin.site.register(Comment_Document)
admin.site.register(bad_keyword)
admin.site.register(Quiz)
admin.site.register(Quiz_questions)
admin.site.register(GPTeen_doc)
admin.site.register(GPTeen_University_doc)
admin.site.register(club)
admin.site.register(club_member)
admin.site.register(club_image)
admin.site.register(club_role)
admin.site.register(club_comment)
admin.site.register(online_class)
admin.site.register(online_class_comment)
admin.site.register(online_class_buyer)
admin.site.register(online_class_homework_submit)
admin.site.register(homework_online_class)
