from django.urls import path
from . import views

urlpatterns = [
    # index
    path('', views.index, name="index"),
    # authenticate
    path('accounts/login', views.Login, name="a_login"),
    path('accounts/sign/up/', views.Signup, name="signup"),
    path('logout/', views.log_out, name="log_out"),
    # like
    path('like/document/<int:id>', views.like_document, name="like_document"),
    path('like/post/<int:id>', views.like_post, name="like_post"),
    path('like/question/<int:id>', views.like_question, name="like_question"),
    path('like/answer/<int:id>', views.like_answer, name="like_answer"),
    # dislike
    path('dislike/document/<int:id>',
         views.dislike_document, name="dislike_document"),
    path('dislike/post/<int:id>', views.dislike_post, name="dislike_post"),
    path('dislike/question/<int:id>',
         views.dislike_question, name="dislike_question"),
    path('dislike/answer/<int:id>', views.dislike_answer, name="dislike_answer"),
    # answer
    path('answer/question/<int:id>', views.answer, name="answer"),
    # comment
    path('comment/post/<int:id>', views.comment_post, name="comment_post"),
    path('comment/document/<int:id>',
         views.comment_document, name="comment_document"),
    # reply_comment
    path('reply/comment/post/<int:id>',
         views.reply_comment_post, name="reply_comment_post"),
    path('reply/comment/document/<int:id>',
         views.reply_comment_document, name="reply_comment_document"),
    # read
    path("view/comment/post/<int:id>",
         views.comment_post_view, name="comment_post_view"),
    path("view/document/<int:id>", views.document_view, name="document_view"),
    path("view/question/<int:id>",
         views.question_view, name="question_view"),
    # create
    path("create/post/", views.post_create, name="create_post"),
    path("create/document/", views.document_create, name="create_document"),
    path("create/question/", views.question_create, name="create_question"),
    # update
    path("update/post/<int:id>", views.update_post, name="update_post"),
    path("update/document/<int:id>", views.update_document, name="update_document"),
    path("update/question/<int:id>", views.update_question, name="update_question"),
    path("update/answer/<int:id>", views.update_answer, name="update_anwer"),
    path("update/comment/post/<int:id>",
         views.update_comment_post, name="update_comment_post"),
    path("update/comment/document/<int:id>",
         views.update_comment_document, name="update_comment_document"),
    # delete
    path("delete/post/<int:id>", views.delete_post, name="delete_post"),
    path("delete/document/<int:id>", views.delete_document, name="delete_document"),
    path("delete/question/<int:id>", views.delete_question, name="delete_question"),
    path("delete/answer/<int:id>", views.delete_answer, name="delete_answer"),
    path("delete/comment/post/<int:id>",
         views.delete_comment_Post, name="delete_comment_post"),
    path("delete/comment/document/<int:id>",
         views.delete_comment_document, name="delete_comment_document"),
    # user
    path("user/<int:id>", views.user_profile, name="user_profile"),
    path("your/profile/", views.your_profile, name="your_profile"),
    path("delete/profile/", views.delete_user, name="delete_profile"),
    path("add/social/media", views.add_social_media, name="add_social_media"),
    path("update/profile", views.update_profile, name="update_profile"),
    # payment
    path("payment/question/<int:id>", views.question_payment, name="pay_question"),
    path("payment/document/<int:id>", views.document_payment, name="pay_document"),
    path("payment/post/<int:id>", views.post_payment, name="pay_post"),
    # list_view
    path("post/",
         views.post_list_view, name="post"),
    path("document/", views.document_list_view, name="document"),
    path("question/",
         views.question_list_view, name="question"),
    # all_error
    path("error/all/", views.all_error, name="all_error"),
    path("check/", views.check, name="check"),
    # staff
    path("staff/", views.staff_index, name="staff_index"),
    path("staff/post/", views.staff_post_list, name="staff_post_list"),
    path("staff/document/", views.staff_document_list, name="staff_document_list"),
    path("staff/question/", views.staff_question_list, name="staff_question_list"),
    path("staff/answer/", views.staff_answer_list, name="staff_answer_list"),
    path("staff/comment/document/", views.staff_comment_document_list,
         name="staff_comment_document_list"),
    path("staff/comment/post/", views.staff_comment_post_list,
         name="staff_comment_post_list"),
    path("staff/document/view/<int:id>",
         views.staff_document_view, name="staff_document_view"),
    path("staff/question/view/<int:id>",
         views.staff_question_view, name="staff_question_view"),
    path("staff/answer/view/<int:id>",
         views.staff_answer_view, name="staff_answer_view"),
    path("staff/comment/document/view/<int:id>",
         views.staff_comment_document_view, name="staff_comment_document_view"),
    path("staff/comment/post/view/<int:id>",
         views.staff_comment_post_view, name="staff_comment_post_view"),
    path("staff/post/done/<int:id>", views.staff_done_post, name="staff_done_post"),
    path("staff/document/done/<int:id>",
         views.staff_done_document, name="staff_done_document"),
    path("staff/question/done/<int:id>",
         views.staff_done_question, name="staff_done_question"),
    path("staff/answer/done/<int:id>",
         views.staff_done_answer, name="staff_done_answer"),
    path("staff/comment/post/done/<int:id>",
         views.staff_done_comment_post, name="staff_done_comment_post"),
    path("staff/comment/document/done/<int:id>",
         views.staff_done_comment_document, name="staff_done_comment_document"),
    path("staff/post/delete/<int:id>",
         views.staff_delete_post, name="staff_delete_post"),
    path("staff/document/delete/<int:id>",
         views.staff_delete_document, name="staff_delete_document"),
    path("staff/question/delete/<int:id>",
         views.staff_delete_question, name="staff_delete_question"),
    path("staff/answer/delete/<int:id>",
         views.staff_delete_answer, name="staff_delete_answer"),
    path("staff/comment/post/delete/<int:id>",
         views.staff_delete_comment_post, name="staff_delete_comment_post"),
    path("staff/comment/document/delete/<int:id>",
         views.staff_delete_comment_document, name="staff_delete_comment_document"),
    # down
    path("down/post/<int:id>", views.down_post, name="down_post"),
    path("down/document/<int:id>", views.down_document, name="down_document"),
    path("down/question/<int:id>", views.down_question, name="down_question"),
    path("down/answer/<int:id>", views.down_answer, name="down_answer"),
    path("down/comment/post/<int:id>",
         views.down_comment_post, name="down_comment_post"),
    path("down/comment/document/<int:id>",
         views.down_comment_document, name="down_comment_document"),
    path("download/document/file/<int:id>",
         views.download_document_file, name="download_document_file"),
    path("download/question/file/<int:id>",
         views.download_question_file, name="download_question_file"),
    path("download/answer/file/<int:id>",
         views.download_answer_file, name="download_answer_file"),
    path("download/staff/document/file/<int:id>",
         views.staff_download_document_file, name="staff_download_document_file"),
    # bill
    path("bill/post/<int:id>/value/<int:value>",
         views.post_bill, name="post_bill"),
    path("bill/question/<int:id>", views.question_bill, name="question_bill"),
    path("bill/document/<int:id>", views.document_bill, name="document_bill"),
    # success
    path("success/<status>", views.success, name="success"),
    path("check/question/<int:id>/", views.check_question, name="check_question"),
    path("ask/gpteen", views.gpteen_input, name="ask_gpteen"),
    path("result/gpteen/<str:prompt>", views.gpteen_answer,
         name="gpteen_answer_result"),
    path("user/honor/", views.user_honor, name="user_honor"),
    path("staff/honor", views.staff_all_honor, name="staff_honor"),
    path("satff/check/honor/<int:id>",
         views.staff_check_honor, name="staff_check_honor"),
    path("create/quiz/", views.make_quiz, name="make_quiz"),
    path("create/question/<int:ques_no>/quiz/<int:quiz_id>",
         views.make_question, name="make_question"),
    path("edit/question/<int:ques_no>/quiz/<int:quiz_id>",
         views.edit_question, name="edit_question"),
    path("delete/question/<int:id>/",
         views.delete_question, name="delete_question"),
    path("delete/quiz/<int:id>", views.delete_quiz, name="delete_quiz"),
    path("quiz/", views.quiz_list, name="quiz"),
    path("quiz/view/<int:id>", views.quiz_view, name="quiz_view"),
    path("practice/question/<int:id>",
         views.quiz_question_view, name="quiz_question_view"),
    path("practice/after/question/<int:id>/point/<int:point>/status/<status>",
         views.quiz_question_after_view, name="quiz_question_after_view"),
    path("gpteen/image/", views.GPTeen_image, name="gpteen_image"),
    path("gpteen/image/result/<int:id>",
         views.GPTeen_image_result, name="gpteen_image_result"),
    path("gpteen/document/", views.GPTeen_document, name="gpteen_document"),
    path("gpteen/document/result/<int:id>",
         views.GPTeen_document_result, name="gpteen_document_result"),
    path("gpteen/university/", views.GPTeen_university, name="gpteen_university"),
    path("gpteen/university/result/score/<score>/category/code/<category_code>/job/<job>/area/<area>",
         views.GPTeen_university_result, name="gpteen_university_result"),
    path("post/<int:id>", views.post_view, name="post_view")
]
