# Generated by Django 4.2.6 on 2024-04-29 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bad_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('twitter', models.CharField(blank=True, max_length=1000, null=True)),
                ('zalo', models.CharField(blank=True, max_length=1000, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('balance', models.FloatField()),
                ('wallet_passcode', models.TextField()),
                ('deleted', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('grade', models.IntegerField()),
                ('price', models.FloatField()),
                ('file', models.FileField(upload_to='files/documents/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=1000)),
                ('comment_counter', models.IntegerField()),
                ('dislike', models.ManyToManyField(related_name='document_dislike', to='social_learning.bio')),
                ('down', models.ManyToManyField(related_name='document_down', to='social_learning.bio')),
            ],
        ),
        migrations.CreateModel(
            name='Education_rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(upload_to='files/questions/')),
                ('grade', models.IntegerField()),
                ('price', models.FloatField()),
                ('answered', models.IntegerField()),
                ('status', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_counter', models.IntegerField()),
                ('dislike', models.ManyToManyField(related_name='question_dislike', to='social_learning.bio')),
                ('down', models.ManyToManyField(related_name='question_down', to='social_learning.bio')),
                ('education_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Education_rank_question', to='social_learning.education_rank')),
                ('like', models.ManyToManyField(related_name='question_like', to='social_learning.bio')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='social_learning.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to='social_learning.bio')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('comment_counter', models.IntegerField()),
                ('dislike', models.ManyToManyField(related_name='post_dislike_related', to='social_learning.bio')),
                ('down', models.ManyToManyField(related_name='post_down', to='social_learning.bio')),
                ('like', models.ManyToManyField(related_name='post_like_related', to='social_learning.bio')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_subject', to='social_learning.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_auth_related', to='social_learning.bio')),
            ],
        ),
        migrations.CreateModel(
            name='hornorable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField()),
                ('content', models.TextField()),
                ('status', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honorable_related', to='social_learning.bio')),
            ],
        ),
        migrations.CreateModel(
            name='have_buy_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_check', to='social_learning.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Document_buyer', to='social_learning.bio')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='edu_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_edu_rank', to='social_learning.education_rank'),
        ),
        migrations.AddField(
            model_name='document',
            name='like',
            field=models.ManyToManyField(related_name='document_like', to='social_learning.bio'),
        ),
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_subject', to='social_learning.subject'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Document_auth', to='social_learning.bio'),
        ),
        migrations.CreateModel(
            name='Comment_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=1000)),
                ('down', models.ManyToManyField(related_name='comment_post_down', to='social_learning.bio')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_related', to='social_learning.post')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_user_related', to='social_learning.bio')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=1000)),
                ('down', models.ManyToManyField(related_name='comment_document_down', to='social_learning.bio')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmt_document', to='social_learning.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_document_user', to='social_learning.bio')),
            ],
        ),
        migrations.AddField(
            model_name='bio',
            name='edu_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_edu_rank', to='social_learning.education_rank'),
        ),
        migrations.AddField(
            model_name='bio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(upload_to='files/answers/')),
                ('choosen', models.IntegerField()),
                ('status', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('dislike', models.ManyToManyField(related_name='answer_dislike', to='social_learning.bio')),
                ('down', models.ManyToManyField(related_name='answer_down', to='social_learning.bio')),
                ('like', models.ManyToManyField(related_name='answer_like', to='social_learning.bio')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_select', to='social_learning.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_user_answer', to='social_learning.bio')),
            ],
        ),
    ]
