# Generated by Django 4.2.6 on 2024-05-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grade', models.IntegerField()),
                ('number_of_question', models.IntegerField()),
                ('edu_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_edu_rank', to='social_learning.education_rank')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_subject', to='social_learning.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_auth', to='social_learning.bio')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
                ('a', models.TextField()),
                ('b', models.TextField()),
                ('c', models.TextField()),
                ('d', models.TextField()),
                ('correct', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz', to='social_learning.quiz')),
            ],
        ),
    ]
